export default {
  abnormalMessage: 'too many logins (max 30 per 24 hours), please contact Govee customer service',
  accNotFound: 'accessory not found',
  alDisabled: 'adaptive lighting disabled due to significant colour change',
  alDisabledScene: 'adaptive lighting disabled due to scene change',
  apiPollingIncrease: 'due to amount of devices, increasing polling to',
  available: 'client enabled',
  availableWithDevices: (n) => `client enabled and found ${n} device(s)`,
  brand: 'Govee',
  btNoPackage: 'required hardware/packages not available',
  btScanDisabled: 'sync for thermo-hygrometer sensors disabled as',
  btScanNoStart: 'could not start sync as',
  btScanNoStop: 'could not stop sync as',
  btScanUnknown: 'reading received for unknown accessory',
  btStart: 'scanning started',
  btStop: 'scanning stopped',
  btTimeout: 'BLE took too long',
  btWrongState: 'BLE adapter not in correct state',
  cfgDef: 'is not a valid number so using default of',
  cfgDup: 'will be ignored since another entry with this ID already exists',
  cfgIgn: 'is not configured correctly so ignoring',
  cfgIgnItem: 'has an invalid entry which will be ignored',
  cfgItem: 'Config entry',
  cfgLow: 'is set too low so increasing to',
  cfgRmv: 'is unused and can be removed',
  cfgQts: 'should not have quotes around its entry',
  clientBusy: 'Skipping sync as client is busy sending updates',
  cmdNotAWS: 'command not supported via AWS',
  cmdNotBLE: 'command not supported via BLE',
  complete: '✓ Setup complete',
  curBatt: 'current battery',
  curBright: 'current brightness',
  curColour: 'current colour',
  curCool: 'current cooling',
  curDisplay: 'current display',
  curFault: 'current fault',
  curHeat: 'current heating',
  curHumi: 'current humidity',
  curLeak: 'current leak',
  curLight: 'current light',
  curLock: 'current lock',
  curScene: 'current scene',
  curSpeed: 'current speed',
  curState: 'current state',
  curSwing: 'current swing',
  curTarg: 'current target',
  curTemp: 'current temperature',
  devAdd: 'has been added to Homebridge',
  devInit: 'initialised with id',
  devInitOpts: 'initialising with options',
  devMaySupp: 'is not currently supported, do create a Github issue with the following info',
  devNotAdd: 'could not be added to Homebridge as',
  devNotConf: 'could not be configured as',
  devNotInit: 'could not be initialised as',
  devNotRef: 'could not be refreshed as',
  devNotRemove: 'could not be removed from Homebridge as',
  devNotRet: 'skipping sync as device status not retrievable',
  devNotUpdated: 'could not be updated as',
  devRemove: 'has been removed from Homebridge',
  disabled: 'To change this, set disablePlugin to false',
  disableClient: 'disabling client as',
  disabling: 'Disabling plugin',
  errGetDevice: 'an unknown error occurred [getDevice()]',
  errGetDevices: 'an unknown error occurred [getDevices()]',
  errUpdateDevice: 'an unknown error occurred [updateDevice()]',
  goveeErr: 'a problem occurred with the Govee server, will try again',
  hbVersionFail: 'Your version of Homebridge is too low - please update to v1.5',
  heaterSimNoSensor: 'you must configure a device ID that provides a temperature reading',
  httpRetry: 'Unable to reach Govee, retrying in 30 seconds',
  initialised: 'Plugin initialised. Setting up accessories...',
  initialising: 'Initialising plugin',
  invalidApiKey: 'Invalid Govee API key',
  labelNo: 'no',
  labelYes: 'yes',
  lanCmdSent: 'command sent to',
  lanDevNotFound: 'device not found in LAN list',
  lanDevRemoved: 'removed device due to connection error',
  lanFoundDevice: 'found device',
  lanParseError: 'could not parse message',
  lanReqError: 'could not request device status as',
  lanServerStarted: 'server started listening on',
  lanUnkDevice: 'received update from unknown device',
  loginSuccess: 'login successful',
  logoutFail: 'could not log out of Govee account as',
  needHTTPClient: 'requires HTTP client',
  newScene: 'new scene code',
  noAPIKey: 'API key not provided',
  noCreds: 'username and/or password not provided',
  noConnMethod: 'no connection method available',
  noDevices: 'no data received from Govee server whilst obtaining devices',
  noDevs: 'No devices found to initialise',
  noExtFunc: 'no externalUpdate function to process incoming update',
  notAWSConn: 'not connected to AWS',
  notAWSSent: 'not using AWS connection as',
  notBLESent: 'not using BLE connection as',
  notLANSent: 'not using LAN connection as',
  noToken: 'no data received from Govee server whilst obtaining token',
  noTokenExists: 'no account token has been retrieved',
  notSuppTurn: 'does not support command [turn]',
  offlineAPI: 'has been reported [offline]',
  onlineAPI: 'has been reported [online]',
  offlineBTConn: 'has been reported [disconnected] via BLE',
  onlineBT: 'has been reported [discoverable] via BLE',
  onlineBTConn: 'has been reported [connected] via BLE',
  pluginNotConf: 'Plugin has not been configured',
  receivingUpdate: 'receiving update',
  sceneCode: 'the AWS code for this scene/mode is shown on the next line(s)',
  sceneCodeWrong: 'scene code not in correct format',
  sendingUpdate: 'sending update',
  skippingAL: 'skipping adaptive lighting update as device is off or kelvin is same as before',
  storageSetupErr: 'Could not setup storage client as',
  storageWriteErr: 'could not save accessory to file as',
  supportColorShort: 'device supports \'color/rgb\' command, let me know on Github with model number',
  supportColorWC: 'device supports \'colorwc\' command, let me know on Github with model number',
  supportLAN: 'device supports LAN commands, let me know on Github with model number',
  syncFail: 'sync failed as',
  viaAL: 'via adaptive lighting',
  zWelcome: [
    'Don\'t forget to ☆ this plugin on GitHub if you\'re finding it useful!',
    'Have a feature request? Visit https://bit.ly/hb-govee-issues to ask!',
    'Interested in sponsoring this plugin? https://github.com/sponsors/bwp91',
    'Join the plugin\'s Discord community! https://discord.gg/cMGhNtZ3tW',
    'Thanks for using this plugin, I hope you find it helpful!',
    'This plugin has been made with ♥ by bwp91 from the UK!',
    'Check out my other Homebridge plugins! https://github.com/bwp91',
    'Have time to give this plugin a review? https://bit.ly/hb-govee-review',
    'This plugin currently has a 4.5☆ rating on HOOBS! https://bit.ly/hb-govee-review',
    'Want to see this plugin in your own language? Let me know!',
  ],
};
