/* jshint -W014, -W033, esversion: 9 */
/* eslint-disable new-cap */
'use strict'

module.exports = {
  accNotFound: 'accessory not found',
  alDisabled: 'adaptive lighting disabled due to significant colour change',
  brand: 'Govee',
  btNoDevices: 'no enabled devices configured',
  btNoPackage: 'required packages not available',
  btStart: 'scanning started',
  btStop: 'scanning stopped',
  btTimeout: 'BLE took too long',
  cfgDef: 'is not a valid number so using default of',
  cfgIgn: 'is not configured correctly so ignoring',
  cfgIgnItem: 'has an invalid entry which will be ignored',
  cfgItem: 'Config entry',
  cfgLow: 'is set too low so increasing to',
  cfgRmv: 'is unused and can be removed',
  cfgQts: 'should not have quotes around its entry',
  clientBusy: 'Skipping sync as client is busy sending updates',
  cmdNotAWS: 'command not supported via AWS',
  cmdNotBLE: 'command not supported via BLE',
  complete: '✓ Setup complete',
  curBright: 'current brightness',
  curColour: 'current colour',
  curScene: 'current scene',
  curState: 'current state',
  devAdd: 'has been added to Homebridge',
  devInit: 'initialised with id',
  devInitOpts: 'initialising with options',
  devNotAdd: 'could not be added to Homebridge as',
  devNotConf: 'could not be configured as',
  devNotControl: 'has been reported [offline] via API, so update may or may not be successful',
  devNotInit: 'could not be initialised as',
  devNotRef: 'could not be refreshed as',
  devNotRemove: 'could not be removed from Homebridge as',
  devNotRet: 'skipping sync as device status not retrievable',
  devNotSupp: 'is not configured for BLE or not supported or by the plugin',
  devNotUpdated: 'could not be updated as',
  devRemove: 'has been removed from Homebridge',
  disabled: 'To change this, set disablePlugin to false',
  disableAPI: 'Disabling API client as',
  disableBT: 'Disabling BLE client as',
  disableHTTP: 'Disabling HTTP client as',
  disabling: 'Disabling plugin',
  errGetDevice: 'an unknown error occurred [getDevice()]',
  errGetDevices: 'an unknown error occurred [getDevices()]',
  errUpdateDevice: 'an unknown error occured [updateDevice()]',
  goveeErr: 'a problem occurred with the Govee server, will try again',
  hbVersionFail: 'Your version of Homebridge is too low - please update to v1.3',
  httpRetry: 'Unable to reach Govee, retrying in 30 seconds',
  identify: 'identify button pressed',
  ignoringUpdate: 'ignoring update',
  initialised: 'Plugin initialised. Setting up accessories...',
  initialising: 'Initialising plugin',
  invalidApiKey: 'Invalid Govee API key',
  noAPIKey: 'API key not provided',
  noBTAdapter: 'no adapter found, see https://bit.ly/hb-govee-bluetooth for info',
  noCreds: 'username and/or password not provided',
  noDevice: 'no data received from Govee server whilst obtaining device',
  noDevices: 'no data received from Govee server whilst obtaining devices',
  noDevList: 'invalid or non-existent device list received',
  noDevs: 'No devices found to initialise',
  notAvailable: 'not available or enabled',
  notAWSSent: 'not sending AWS update as',
  notBTSent: 'reverting to API as',
  noToken: 'no data received from Govee server whilst obtaining token',
  noTokenExists: 'no account token has been retrieved',
  notSuppBrightness: 'does not support command [brightness]',
  notSuppColour: 'does not support command [color]',
  notSuppTurn: 'does not support command [turn]',
  offlineAPI: 'has been reported [offline] via API',
  onlineAPI: 'has been reported [online] via API',
  offlineBTConn: 'has been reported [disconnected] via BLE',
  onlineBT: 'has been reported [discoverable] via BLE',
  onlineBTConn: 'has been reported [connected] via BLE',
  pluginNotConf: 'Plugin has not been configured',
  receivingUpdate: 'receiving update',
  sceneCode: 'the code for this scene/mode is shown on the next line(s)',
  sceneCodeWrong: 'scene code not in correct format',
  sendingUpdate: '[API] sending update',
  sendingUpdateAWS: '[AWS] sending update',
  sendingUpdateBT: '[BLE] sending update',
  skippingAL: 'skipping adaptive lighting update as device is off or kelvin is same as before',
  syncFailed: 'Sync process failed as',
  viaAL: 'via adaptive lighting',
  zWelcome: [
    "Don't forget to ☆ this plugin on GitHub if you're finding it useful!",
    'Have a feature request? Visit http://bit.ly/hb-govee-issues to ask!',
    'Interested in sponsoring this plugin? https://github.com/sponsors/bwp91',
    "Join the plugin's Discord community! https://discord.gg/cMGhNtZ3tW",
    'Thanks for using this plugin, I hope you find it helpful!',
    'This plugin has been made with ♥ by bwp91 from the UK!',
    'Have time to give this plugin a review? http://bit.ly/hb-govee-review',
    'Want to see this plugin in your own language? Let me know!'
  ]
}
